return {
    "lsp.conform",
    "lsp.mason",
    "lsp.mason-lspconfig",
    "lsp.mason-tool-installer",
    "lsp.nvim-cmp",
    "lsp.nvim-lint",
    "lsp.nvim-lspconfig",
    "lsp.nvim-treesitter",
    "plugins.codeium",
    "plugins.leap",
    "plugins.mini",
    "plugins.neotree",
    "plugins.oil-nvim",
    "plugins.ollama-nvim",
    "plugins.personal_config",
    "plugins.telescope",
    "plugins.which-key",
    "ui.colorscheme",
    "ui.dressing",
    "ui.headlines",
    "ui.indent-blanklines",
    "ui.log-highlighter",
    "ui.lualine",
    "ui.twilight",
    "ui.vim-illuminate",
    "ui.virt-column",
    "ui.wrapwidth",
    "ui.zen-mode",
    -- "ui.nivm-notify",
    -- "ui.noice",
}
