return {
    -- "lsp.conform",
    -- "lsp.mason",
    -- "lsp.mason-lspconfig",
    -- "lsp.mason-tool-installer",
    -- "lsp.nvim-cmp",
    -- "lsp.nvim-lint",
    -- "lsp.nvim-lspconfig",
    -- "lsp.nvim-treesitter",
    -- "plugins.neotree",
    -- "plugins.oil-nvim",
    -- "plugins.leap",
    -- "plugins.mini",
    -- "plugins.personal_config",
    "plugins.telescope",
    -- "plugins.which-key",
    -- "ui.colorscheme",
    "ui.dressing",
    -- "ui.headlines",
    -- "ui.indent-blanklines",
    "ui.lualine",
    -- "ui.nivm-notify",
    -- "ui.noice",
    -- "ui.twilight",
    -- "ui.vim-illuminate",
    -- "ui.virt-column",
    -- "ui.wrapwidth",
    -- "ui.zen-mode",
    "plugins.ollama-nvim",
}
